# Generated by Django 3.1.3 on 2020-11-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('correta', models.CharField(max_length=1, verbose_name='Questao correta')),
                ('solucao', models.TextField(verbose_name='solucao')),
                ('nivel', models.IntegerField(verbose_name='nivel')),
                ('a', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
                ('d', models.TextField()),
            ],
        ),
    ]
